
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Emma
 */
public class MonopolyGUI extends javax.swing.JFrame {

    /**
     * Creates new form MonopolyGUI
     */
    public MonopolyGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        space2 = new javax.swing.JLabel();
        space4 = new javax.swing.JLabel();
        space3 = new javax.swing.JLabel();
        space5 = new javax.swing.JLabel();
        space6 = new javax.swing.JLabel();
        space7 = new javax.swing.JLabel();
        space8 = new javax.swing.JLabel();
        space9 = new javax.swing.JLabel();
        space10 = new javax.swing.JLabel();
        space11 = new javax.swing.JLabel();
        space12 = new javax.swing.JLabel();
        space13 = new javax.swing.JLabel();
        space14 = new javax.swing.JLabel();
        space15 = new javax.swing.JLabel();
        space16 = new javax.swing.JLabel();
        space17 = new javax.swing.JLabel();
        space18 = new javax.swing.JLabel();
        space19 = new javax.swing.JLabel();
        space20 = new javax.swing.JLabel();
        space21 = new javax.swing.JLabel();
        space22 = new javax.swing.JLabel();
        space23 = new javax.swing.JLabel();
        space24 = new javax.swing.JLabel();
        space25 = new javax.swing.JLabel();
        space26 = new javax.swing.JLabel();
        space27 = new javax.swing.JLabel();
        space28 = new javax.swing.JLabel();
        space29 = new javax.swing.JLabel();
        space30 = new javax.swing.JLabel();
        space31 = new javax.swing.JLabel();
        space32 = new javax.swing.JLabel();
        space33 = new javax.swing.JLabel();
        space34 = new javax.swing.JLabel();
        space35 = new javax.swing.JLabel();
        space36 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        space37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 623));
        setResizable(false);

        space2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/space2.png"))); // NOI18N
        space2.setText("jLabel2");
        space2.setToolTipText("Community Chest");
        space2.setPreferredSize(new java.awt.Dimension(48, 80));

        space4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceBottom.png"))); // NOI18N
        space4.setText("jLabel2");
        space4.setPreferredSize(new java.awt.Dimension(48, 80));

        space3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/space3.png"))); // NOI18N
        space3.setText("jLabel2");
        space3.setToolTipText("Baltic Avenue");
        space3.setPreferredSize(new java.awt.Dimension(48, 80));

        space5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/space6.png"))); // NOI18N
        space5.setText("jLabel2");
        space5.setToolTipText("We Don't Say That Anymore Avenue");
        space5.setPreferredSize(new java.awt.Dimension(48, 80));

        space6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/space8.png"))); // NOI18N
        space6.setText("jLabel2");
        space6.setToolTipText("Vermont Avenue");
        space6.setPreferredSize(new java.awt.Dimension(48, 80));

        space7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceBottom.png"))); // NOI18N
        space7.setText("jLabel2");
        space7.setPreferredSize(new java.awt.Dimension(48, 80));

        space8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceBottom.png"))); // NOI18N
        space8.setText("jLabel2");
        space8.setPreferredSize(new java.awt.Dimension(48, 80));

        space9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/space9.png"))); // NOI18N
        space9.setText("jLabel2");
        space9.setToolTipText("Connecticut Avenue");
        space9.setPreferredSize(new java.awt.Dimension(48, 80));

        space10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceTop.png"))); // NOI18N
        space10.setText("jLabel2");
        space10.setPreferredSize(new java.awt.Dimension(48, 80));

        space11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceTop.png"))); // NOI18N
        space11.setText("jLabel2");
        space11.setPreferredSize(new java.awt.Dimension(48, 80));

        space12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceTop.png"))); // NOI18N
        space12.setText("jLabel2");
        space12.setPreferredSize(new java.awt.Dimension(48, 80));

        space13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceTop.png"))); // NOI18N
        space13.setText("jLabel2");
        space13.setPreferredSize(new java.awt.Dimension(48, 80));

        space14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceTop.png"))); // NOI18N
        space14.setText("jLabel2");
        space14.setPreferredSize(new java.awt.Dimension(48, 80));

        space15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceTop.png"))); // NOI18N
        space15.setText("jLabel2");
        space15.setPreferredSize(new java.awt.Dimension(48, 80));

        space16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceTop.png"))); // NOI18N
        space16.setText("jLabel2");
        space16.setPreferredSize(new java.awt.Dimension(48, 80));

        space17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceTop.png"))); // NOI18N
        space17.setText("jLabel2");
        space17.setPreferredSize(new java.awt.Dimension(48, 80));

        space18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceTop.png"))); // NOI18N
        space18.setText("jLabel2");
        space18.setPreferredSize(new java.awt.Dimension(48, 80));

        space19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceRight.png"))); // NOI18N
        space19.setText("jLabel2");
        space19.setPreferredSize(new java.awt.Dimension(80, 48));

        space20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceRight.png"))); // NOI18N
        space20.setText("jLabel2");
        space20.setPreferredSize(new java.awt.Dimension(80, 48));

        space21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceRight.png"))); // NOI18N
        space21.setText("jLabel2");
        space21.setPreferredSize(new java.awt.Dimension(80, 48));

        space22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceRight.png"))); // NOI18N
        space22.setText("jLabel2");
        space22.setPreferredSize(new java.awt.Dimension(80, 48));

        space23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceRight.png"))); // NOI18N
        space23.setText("jLabel2");
        space23.setPreferredSize(new java.awt.Dimension(80, 48));

        space24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceRight.png"))); // NOI18N
        space24.setText("jLabel2");
        space24.setPreferredSize(new java.awt.Dimension(80, 48));

        space25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceRight.png"))); // NOI18N
        space25.setText("jLabel2");
        space25.setPreferredSize(new java.awt.Dimension(80, 48));

        space26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceRight.png"))); // NOI18N
        space26.setText("jLabel2");
        space26.setPreferredSize(new java.awt.Dimension(80, 48));

        space27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceRight.png"))); // NOI18N
        space27.setText("jLabel2");
        space27.setPreferredSize(new java.awt.Dimension(80, 48));

        space28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceLeft.png"))); // NOI18N
        space28.setText("jLabel2");
        space28.setPreferredSize(new java.awt.Dimension(80, 48));

        space29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceLeft.png"))); // NOI18N
        space29.setText("jLabel2");
        space29.setPreferredSize(new java.awt.Dimension(80, 48));

        space30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceLeft.png"))); // NOI18N
        space30.setText("jLabel2");
        space30.setPreferredSize(new java.awt.Dimension(80, 48));

        space31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceLeft.png"))); // NOI18N
        space31.setText("jLabel2");
        space31.setPreferredSize(new java.awt.Dimension(80, 48));

        space32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceLeft.png"))); // NOI18N
        space32.setText("jLabel2");
        space32.setPreferredSize(new java.awt.Dimension(80, 48));

        space33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceLeft.png"))); // NOI18N
        space33.setText("jLabel2");
        space33.setPreferredSize(new java.awt.Dimension(80, 48));

        space34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceLeft.png"))); // NOI18N
        space34.setText("jLabel2");
        space34.setPreferredSize(new java.awt.Dimension(80, 48));

        space35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceLeft.png"))); // NOI18N
        space35.setText("jLabel2");
        space35.setPreferredSize(new java.awt.Dimension(80, 48));

        space36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceLeft.png"))); // NOI18N
        space36.setText("jLabel2");
        space36.setPreferredSize(new java.awt.Dimension(80, 48));

        jButton1.setText("Roll Dice");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cornerSpace.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goSpace.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cornerSpace.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cornerSpace.png"))); // NOI18N
        jLabel4.setText("jLabel1");
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 80));

        space37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/space1.png"))); // NOI18N
        space37.setText("jLabel2");
        space37.setToolTipText("Mediteranean Avenue ");
        space37.setPreferredSize(new java.awt.Dimension(48, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(space9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(space19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(space20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(space21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(space22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(175, 175, 175)
                                .addComponent(space23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(space24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(space25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(space26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(space27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(space18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(space17, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(space19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(space23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(0, 0, 0)
                        .addComponent(space24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(space2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(space3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(space4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(space8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(space5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(space7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(space6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(space9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(space37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(space30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(space29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        space5.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonopolyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonopolyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonopolyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonopolyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonopolyGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel space10;
    private javax.swing.JLabel space11;
    private javax.swing.JLabel space12;
    private javax.swing.JLabel space13;
    private javax.swing.JLabel space14;
    private javax.swing.JLabel space15;
    private javax.swing.JLabel space16;
    private javax.swing.JLabel space17;
    private javax.swing.JLabel space18;
    private javax.swing.JLabel space19;
    private javax.swing.JLabel space2;
    private javax.swing.JLabel space20;
    private javax.swing.JLabel space21;
    private javax.swing.JLabel space22;
    private javax.swing.JLabel space23;
    private javax.swing.JLabel space24;
    private javax.swing.JLabel space25;
    private javax.swing.JLabel space26;
    private javax.swing.JLabel space27;
    private javax.swing.JLabel space28;
    private javax.swing.JLabel space29;
    private javax.swing.JLabel space3;
    private javax.swing.JLabel space30;
    private javax.swing.JLabel space31;
    private javax.swing.JLabel space32;
    private javax.swing.JLabel space33;
    private javax.swing.JLabel space34;
    private javax.swing.JLabel space35;
    private javax.swing.JLabel space36;
    private javax.swing.JLabel space37;
    private javax.swing.JLabel space4;
    private javax.swing.JLabel space5;
    private javax.swing.JLabel space6;
    private javax.swing.JLabel space7;
    private javax.swing.JLabel space8;
    private javax.swing.JLabel space9;
    // End of variables declaration//GEN-END:variables
}
